services:
  - type: web
    name: warranty-letter-editor
    env: node
    buildCommand: npm run setup && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: false
